version: '3.1'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "9001:9001"
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/postgres
    depends_on:
      - db

volumes:
  pgdata:
